version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency_name: "org.springframework.boot:spring-boot-starter-parent"
        versions: [2.4.0,]