version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: main
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: step1_sdn-ogm_imperative
  ignore:
  - dependency-name: org.springframework.boot:spring-boot-starter-parent
    versions:
    - "> 2.3.7.RELEASE, < 3"
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: step2_sdn_imperative
