= Migration from SDN/OGM to SDN 6

This project assumes that the given application is based on a Spring Boot version 2.3 or below
and has the Spring Data Neo4j Spring Boot starter dependency declared:
```
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-data-neo4j</artifactId>
</dependency>
```

== Features not migrated because we do not consider adapting them

* Auto Index
+
There is no benefit in auto generating indexes/constraint from within the mapping framework.
This should be done directly on the database side.

Consider to use https://github.com/michael-simons/neo4j-migrations for even more powerful database versioning.

== Features with different behavior

* `RelationshipEntity` gets replaced by `RelationshipProperties`
+
As an intended consequence a relationship cannot be the access point of a repository or template anymore.

== Detailed migrations

=== Dependency

Update Spring Boot version to 2.4.
The current version available as of this writing is `2.4.0-M4` that provides Spring Data Neo4j 6 RC2.

=== NodeEntity

Correct imports in the entities:

* Same types
    ** `org.neo4j.ogm.annotation.Id` -> `org.neo4j.springframework.data.core.schema.Id`
    ** `org.neo4j.ogm.annotation.GeneratedValue` -> `org.neo4j.springframework.data.core.schema.GeneratedValue`
    ** `org.neo4j.ogm.annotation.Property` -> `org.neo4j.springframework.data.core.schema.Property`
    ** `org.neo4j.ogm.annotation.Version` -> `org.springframework.data.annotation.Version`
    ** `org.neo4j.ogm.annotation.Relationship` -> `org.neo4j.springframework.data.core.schema.Relationship`
* Other types
    ** `org.neo4j.ogm.annotation.typeconversion.Convert` -> implementation of `GenericConverter` as a global converter
    ** `org.neo4j.ogm.annotation.NodeEntity` -> `org.neo4j.springframework.data.core.schema.Node`

=== RelationshipEntity

Rewrite `RelationshipEntity` to `RelationshipProperty`.
Put `List<RelationshipPropertyAnnotatedClass>` as you would declare a `RelationshipEntity`, but provide a `@TargetNode` information in the class to point to the target entity.
```
@TargetNode
TargetClass targetClass;
```

== Repositories

Correct imports in repositories of same classes like `Neo4jRepository` / `@Query`

=== Usage of Neo4j-OGM's `SessionFactory` or `Session`

Replace `SessionFactory` with direct Java driver access, or the new abstraction layers `Neo4jClient` or `Neo4jTemplate`.

=== _application.properties_
Use Spring Boot's driver auto configuration properties instead of the SDN/Neo4j-OGM properties:

```
# old
#spring.data.neo4j.uri=bolt://localhost:7687
#spring.data.neo4j.username=neo4j
#spring.data.neo4j.password=secret

# new
spring.neo4j.uri=neo4j://localhost:7687
spring.neo4j.authentication.username=neo4j
spring.neo4j.authentication.password=secret
```
